### ISSUE TITLE
Highlighting breaks on comments, empty lines

### ISSUE THREAD

**Issue by FilippoBonazziSUSE** [Fymyte/mbsync.vim#1]
Hi, thanks for the nice plugin. I tried using it but I immediately noticed that it breaks on comments and empty lines in a perfectly valid configuration file.

Straightforward case, all good:
![20220928_16h33m31s_grim](https://user-images.githubusercontent.com/101266837/192807640-e3a093d3-5570-42c9-a34e-8537915b5208.png)

Adding a comment:
![20220928_16h33m51s_grim](https://user-images.githubusercontent.com/101266837/192807743-3d24c192-9897-4797-b36b-cb400b0f33ea.png)
The comment is now picked up as an error.

Adding an empty line:
![20220928_16h34m15s_grim](https://user-images.githubusercontent.com/101266837/192807860-51807644-a3ef-4529-9261-99d72ea500f5.png)
Now everything following the empty line is broken.

**Comment by Fymyte** [comment]
Thanks for the report I will try to fix it this week

**Comment by Fymyte** [comment]
Comment: Fixed by c3175fb

For blank lines, I disagree. As stated by the man page: "Sections are started by a section keyword and are terminated by an empty line or end of file."
So after a blank line, your can only have a new section, or an error
I don't know if `mbsync` consider this as a valid config file but I think this should follow the instructions in the man page.

**Comment by FilippoBonazziSUSE** [comment]
Thanks for the fix. Agreed about the blank lines, it was a bad example.
